version: '3'
services:
  flyway:
    image: michaelruocco/flyway-wait-docker
    container_name: flyway
    environment:
      DB_USER: root
      DB_PASSWORD: 1234
      DB_HOST: app_db
      DB_DATABASE: web_template
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/sql
    command: ["migrate"]

  db:
    image: mysql
    container_name: app_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=web_template

  app:
    image: michaelruocco/web-template
    container_name: app
    ports:
      - 8090:8080
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    depends_on:
      - flyway