server:
  applicationContextPath: /web-template
  applicationConnectors:
  - type: http
    port: 8090

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3307/web_template

swagger:
  resourcePackage: uk.co.mruoc.resources.rest

logging:
  level: INFO