server:
  applicationContextPath: /
  applicationConnectors:
  - type: http
    port: 80

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: 1234
  url: jdbc:mysql://db/web_template?useSSL=false

swagger:
  resourcePackage: uk.co.mruoc.resources.rest

logging:
  level: INFO
