template: Hello, %s!
defaultName: Stranger

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3307/web_template

swagger:
  resourcePackage: uk.co.mruoc.resources