template: web-template

server:
  type: simple
  applicationContextPath: /web-template
  connector:
    type: http
    port: 8090

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3307/web_template

swagger:
  resourcePackage: uk.co.mruoc.resources